//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fyp.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: event certificate or report.
        /// </summary>
        internal static string ApplAttachmentNote {
            get {
                return ResourceManager.GetString("ApplAttachmentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} member(s) will be awarded with.
        /// </summary>
        internal static string AwardBadge_Note {
            get {
                return ResourceManager.GetString("AwardBadge_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Button_Approve {
            get {
                return ResourceManager.GetString("Button_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Button_Confirm {
            get {
                return ResourceManager.GetString("Button_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Badge.
        /// </summary>
        internal static string Button_CreateBadge {
            get {
                return ResourceManager.GetString("Button_CreateBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string Button_DeleteAccount {
            get {
                return ResourceManager.GetString("Button_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export E-Testimonial.
        /// </summary>
        internal static string Button_ExportTestimonial {
            get {
                return ResourceManager.GetString("Button_ExportTestimonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Up.
        /// </summary>
        internal static string Button_LevelUp {
            get {
                return ResourceManager.GetString("Button_LevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Button_Otp_Verify {
            get {
                return ResourceManager.GetString("Button_Otp_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Button_Register {
            get {
                return ResourceManager.GetString("Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Button_Reject {
            get {
                return ResourceManager.GetString("Button_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string Button_ResetPassword {
            get {
                return ResourceManager.GetString("Button_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’m satisfied, proceed.
        /// </summary>
        internal static string Button_SatisfiedAnalysis {
            get {
                return ResourceManager.GetString("Button_SatisfiedAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string Button_SaveChanges {
            get {
                return ResourceManager.GetString("Button_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send OTP.
        /// </summary>
        internal static string Button_SendOTP {
            get {
                return ResourceManager.GetString("Button_SendOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Password Reset Email.
        /// </summary>
        internal static string Button_SendResetEmail {
            get {
                return ResourceManager.GetString("Button_SendResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Default Language.
        /// </summary>
        internal static string Button_SetDefault {
            get {
                return ResourceManager.GetString("Button_SetDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Badge.
        /// </summary>
        internal static string Button_Unlock {
            get {
                return ResourceManager.GetString("Button_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’m unsatisfied, cancel.
        /// </summary>
        internal static string Button_UnsatisfiedAnalysis {
            get {
                return ResourceManager.GetString("Button_UnsatisfiedAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Button_Upload {
            get {
                return ResourceManager.GetString("Button_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload and Analyze.
        /// </summary>
        internal static string Button_UploadAnalyze {
            get {
                return ResourceManager.GetString("Button_UploadAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Button_Verify {
            get {
                return ResourceManager.GetString("Button_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Result.
        /// </summary>
        internal static string Button_ViewResult {
            get {
                return ResourceManager.GetString("Button_ViewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: This will permanently disable your account. Are you absolutely sure?.
        /// </summary>
        internal static string Confirmation_DeleteAccount {
            get {
                return ResourceManager.GetString("Confirmation_DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered is incorrect. Please try again..
        /// </summary>
        internal static string Error_IncorrectPassword {
            get {
                return ResourceManager.GetString("Error_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your current password..
        /// </summary>
        internal static string Error_PasswordRequired {
            get {
                return ResourceManager.GetString("Error_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait 1 minute before requesting another password reset..
        /// </summary>
        internal static string Error_WaitBeforeReset {
            get {
                return ResourceManager.GetString("Error_WaitBeforeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in the list? Please contact your supervisor to add a new event..
        /// </summary>
        internal static string EventNote {
            get {
                return ResourceManager.GetString("EventNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement Application.
        /// </summary>
        internal static string Heading_AchievementApplication {
            get {
                return ResourceManager.GetString("Heading_AchievementApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Course.
        /// </summary>
        internal static string Heading_AddCourse {
            get {
                return ResourceManager.GetString("Heading_AddCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award Badges in Batch.
        /// </summary>
        internal static string Heading_AwardBadges {
            get {
                return ResourceManager.GetString("Heading_AwardBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Information.
        /// </summary>
        internal static string Heading_BadgeInfo {
            get {
                return ResourceManager.GetString("Heading_BadgeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges Gallery.
        /// </summary>
        internal static string Heading_BadgesGallery {
            get {
                return ResourceManager.GetString("Heading_BadgesGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Course.
        /// </summary>
        internal static string Heading_CompletedCourses {
            get {
                return ResourceManager.GetString("Heading_CompletedCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Customization.
        /// </summary>
        internal static string Heading_ContentCus {
            get {
                return ResourceManager.GetString("Heading_ContentCus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Management.
        /// </summary>
        internal static string Heading_CourseManagement {
            get {
                return ResourceManager.GetString("Heading_CourseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Badge.
        /// </summary>
        internal static string Heading_CreateBadge {
            get {
                return ResourceManager.GetString("Heading_CreateBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Badge.
        /// </summary>
        internal static string Heading_EditBadge {
            get {
                return ResourceManager.GetString("Heading_EditBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string Heading_GeneralSettings {
            get {
                return ResourceManager.GetString("Heading_GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction Media.
        /// </summary>
        internal static string Heading_IntroMedia {
            get {
                return ResourceManager.GetString("Heading_IntroMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Recent Applications.
        /// </summary>
        internal static string Heading_ListOfRecentApplications {
            get {
                return ResourceManager.GetString("Heading_ListOfRecentApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of User Accounts.
        /// </summary>
        internal static string Heading_ListOfUserAccounts {
            get {
                return ResourceManager.GetString("Heading_ListOfUserAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Badges.
        /// </summary>
        internal static string Heading_ManageBadge {
            get {
                return ResourceManager.GetString("Heading_ManageBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Achievement Information.
        /// </summary>
        internal static string Heading_MemberAchievement {
            get {
                return ResourceManager.GetString("Heading_MemberAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Course .
        /// </summary>
        internal static string Heading_MyCourse {
            get {
                return ResourceManager.GetString("Heading_MyCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Dashboard.
        /// </summary>
        internal static string Heading_MyDashboard {
            get {
                return ResourceManager.GetString("Heading_MyDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Personal Information.
        /// </summary>
        internal static string Heading_PersonalInfo {
            get {
                return ResourceManager.GetString("Heading_PersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before we proceed....
        /// </summary>
        internal static string Heading_Proceed {
            get {
                return ResourceManager.GetString("Heading_Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Details.
        /// </summary>
        internal static string Heading_ReviewApp {
            get {
                return ResourceManager.GetString("Heading_ReviewApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1 of 2: All Image Analysis Result.
        /// </summary>
        internal static string Heading_Step1Testimonial {
            get {
                return ResourceManager.GetString("Heading_Step1Testimonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2 of 2: Testimonial Customisation.
        /// </summary>
        internal static string Heading_Step2Testimonial {
            get {
                return ResourceManager.GetString("Heading_Step2Testimonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonial Certificate.
        /// </summary>
        internal static string Heading_TestimonialTemp {
            get {
                return ResourceManager.GetString("Heading_TestimonialTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account Security Settings.
        /// </summary>
        internal static string Heading_UpdateAccountSecurity {
            get {
                return ResourceManager.GetString("Heading_UpdateAccountSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Your Identity.
        /// </summary>
        internal static string Heading_VerifyIdentity {
            get {
                return ResourceManager.GetString("Heading_VerifyIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out your Achievement Dashboard to learn more!.
        /// </summary>
        internal static string Hyperlink_AchievementDashboardText {
            get {
                return ResourceManager.GetString("Hyperlink_AchievementDashboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Achievements Content.
        /// </summary>
        internal static string Hyperlink_Achievements {
            get {
                return ResourceManager.GetString("Hyperlink_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Courses Content.
        /// </summary>
        internal static string Hyperlink_Courses {
            get {
                return ResourceManager.GetString("Hyperlink_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Events Content.
        /// </summary>
        internal static string Hyperlink_Events {
            get {
                return ResourceManager.GetString("Hyperlink_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will recommend events and courses based on your preference settings!.
        /// </summary>
        internal static string InterestNote {
            get {
                return ResourceManager.GetString("InterestNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Label_AAEvent {
            get {
                return ResourceManager.GetString("Label_AAEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Outcome.
        /// </summary>
        internal static string Label_AALearningOutcome {
            get {
                return ResourceManager.GetString("Label_AALearningOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Label_AARole {
            get {
                return ResourceManager.GetString("Label_AARole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Attachments.
        /// </summary>
        internal static string Label_AAUploadAttachment {
            get {
                return ResourceManager.GetString("Label_AAUploadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string Label_Achievements {
            get {
                return ResourceManager.GetString("Label_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant Name.
        /// </summary>
        internal static string Label_ApplicantName {
            get {
                return ResourceManager.GetString("Label_ApplicantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID.
        /// </summary>
        internal static string Label_ApplicationID {
            get {
                return ResourceManager.GetString("Label_ApplicationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of Interest.
        /// </summary>
        internal static string Label_AreaOfInterest {
            get {
                return ResourceManager.GetString("Label_AreaOfInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment(s).
        /// </summary>
        internal static string Label_Attachments {
            get {
                return ResourceManager.GetString("Label_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Description.
        /// </summary>
        internal static string Label_BadgeDesc {
            get {
                return ResourceManager.GetString("Label_BadgeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Name.
        /// </summary>
        internal static string Label_BadgeName {
            get {
                return ResourceManager.GetString("Label_BadgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badge Icon.
        /// </summary>
        internal static string Label_BadgePicture {
            get {
                return ResourceManager.GetString("Label_BadgePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges Earned.
        /// </summary>
        internal static string Label_BadgesEarned {
            get {
                return ResourceManager.GetString("Label_BadgesEarned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses Completed.
        /// </summary>
        internal static string Label_CoursesCompleted {
            get {
                return ResourceManager.GetString("Label_CoursesCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Level.
        /// </summary>
        internal static string Label_CurrentLevel {
            get {
                return ResourceManager.GetString("Label_CurrentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Level.
        /// </summary>
        internal static string Label_CurrentLevel1 {
            get {
                return ResourceManager.GetString("Label_CurrentLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password:.
        /// </summary>
        internal static string Label_CurrentPassword {
            get {
                return ResourceManager.GetString("Label_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string Label_EndDate {
            get {
                return ResourceManager.GetString("Label_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        internal static string Label_EventName {
            get {
                return ResourceManager.GetString("Label_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string Label_Font {
            get {
                return ResourceManager.GetString("Label_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction Material(s).
        /// </summary>
        internal static string Label_IntroMedia {
            get {
                return ResourceManager.GetString("Label_IntroMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string Label_Languages {
            get {
                return ResourceManager.GetString("Label_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member since:.
        /// </summary>
        internal static string Label_MemberSince {
            get {
                return ResourceManager.GetString("Label_MemberSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No templates found. Click &apos;Add New Template&apos; to create your first certificate template..
        /// </summary>
        internal static string Label_NoTemplate {
            get {
                return ResourceManager.GetString("Label_NoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Logo.
        /// </summary>
        internal static string Label_OrgLogo {
            get {
                return ResourceManager.GetString("Label_OrgLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        internal static string Label_OrgName {
            get {
                return ResourceManager.GetString("Label_OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the 6-digit code.
        /// </summary>
        internal static string Label_Otp_PinNumber {
            get {
                return ResourceManager.GetString("Label_Otp_PinNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Label_PhoneNumber {
            get {
                return ResourceManager.GetString("Label_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Number.
        /// </summary>
        internal static string Label_PinNumber {
            get {
                return ResourceManager.GetString("Label_PinNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Awarded.
        /// </summary>
        internal static string Label_Points {
            get {
                return ResourceManager.GetString("Label_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment(s).
        /// </summary>
        internal static string Label_PreviousComments {
            get {
                return ResourceManager.GetString("Label_PreviousComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        internal static string Label_ProfilePicture {
            get {
                return ResourceManager.GetString("Label_ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Label_Pw {
            get {
                return ResourceManager.GetString("Label_Pw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Label_Role {
            get {
                return ResourceManager.GetString("Label_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Label_SecurityAnswer {
            get {
                return ResourceManager.GetString("Label_SecurityAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Question.
        /// </summary>
        internal static string Label_SecurityQuestion {
            get {
                return ResourceManager.GetString("Label_SecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Label_StartDate {
            get {
                return ResourceManager.GetString("Label_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template PDF.
        /// </summary>
        internal static string Label_TestimonialPDF {
            get {
                return ResourceManager.GetString("Label_TestimonialPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Image.
        /// </summary>
        internal static string Label_TestimonialTemp {
            get {
                return ResourceManager.GetString("Label_TestimonialTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Label_Theme {
            get {
                return ResourceManager.GetString("Label_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Label_Username {
            get {
                return ResourceManager.GetString("Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to view achievement application status and history.
        /// </summary>
        internal static string Link_AchievementHistory {
            get {
                return ResourceManager.GetString("Link_AchievementHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Login.
        /// </summary>
        internal static string Link_BackToLogin {
            get {
                return ResourceManager.GetString("Link_BackToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up for New Account.
        /// </summary>
        internal static string Link_CreateAcc {
            get {
                return ResourceManager.GetString("Link_CreateAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Account.
        /// </summary>
        internal static string Link_DeactivateAccount {
            get {
                return ResourceManager.GetString("Link_DeactivateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password? Click here to reset.
        /// </summary>
        internal static string Link_ForgotPassword {
            get {
                return ResourceManager.GetString("Link_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Login here..
        /// </summary>
        internal static string Link_Login {
            get {
                return ResourceManager.GetString("Link_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Login via Email.
        /// </summary>
        internal static string Link_LoginEmail {
            get {
                return ResourceManager.GetString("Link_LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Login via Phone Number.
        /// </summary>
        internal static string Link_LoginHP {
            get {
                return ResourceManager.GetString("Link_LoginHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn’t receive a code? Click here to send a new code.
        /// </summary>
        internal static string Link_Otp_ResendCode {
            get {
                return ResourceManager.GetString("Link_Otp_ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Reset Password Link.
        /// </summary>
        internal static string Link_ResetPassword {
            get {
                return ResourceManager.GetString("Link_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Link_Review {
            get {
                return ResourceManager.GetString("Link_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string Link_SelectAll {
            get {
                return ResourceManager.GetString("Link_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to access Template Analyzer.
        /// </summary>
        internal static string Link_TestimonialTemp {
            get {
                return ResourceManager.GetString("Link_TestimonialTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string Link_ViewDetails {
            get {
                return ResourceManager.GetString("Link_ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Page_Title {
            get {
                return ResourceManager.GetString("Login_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login via Phone Number.
        /// </summary>
        internal static string Login1_Heading {
            get {
                return ResourceManager.GetString("Login1_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First time here? You can login via Phone Number directly!.
        /// </summary>
        internal static string Login1_Info {
            get {
                return ResourceManager.GetString("Login1_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login via Email.
        /// </summary>
        internal static string Login2_Heading {
            get {
                return ResourceManager.GetString("Login2_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can also login via Phone Number directly!.
        /// </summary>
        internal static string Login2_Info {
            get {
                return ResourceManager.GetString("Login2_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        internal static string Nav_Achievements {
            get {
                return ResourceManager.GetString("Nav_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Settings.
        /// </summary>
        internal static string Nav_AdminSettings {
            get {
                return ResourceManager.GetString("Nav_AdminSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        internal static string Nav_Courses {
            get {
                return ResourceManager.GetString("Nav_Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Nav_Events {
            get {
                return ResourceManager.GetString("Nav_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a guide to members about the organisation’s member achievement and level system that is displayed in the information page. We recommend including information on how to gain points and level up for your organisation’s business rules..
        /// </summary>
        internal static string Note_IntroMedia {
            get {
                return ResourceManager.GetString("Note_IntroMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly provide the following information..
        /// </summary>
        internal static string Note_ProceedTip {
            get {
                return ResourceManager.GetString("Note_ProceedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use our analyzer to customize your testimonial certifica tetemplate.
        /// </summary>
        internal static string Note_TestimonialTemp {
            get {
                return ResourceManager.GetString("Note_TestimonialTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the 6-digit code.
        /// </summary>
        internal static string Otp_PinNumber_Label {
            get {
                return ResourceManager.GetString("Otp_PinNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn’t receive a code? Click here to send a new code.
        /// </summary>
        internal static string Otp_ResendCode_Link {
            get {
                return ResourceManager.GetString("Otp_ResendCode_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before we proceed with the changes....
        /// </summary>
        internal static string Otp_Verification_Heading {
            get {
                return ResourceManager.GetString("Otp_Verification_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the 6-digit code sent to you at {0}.
        /// </summary>
        internal static string Otp_Verification_Subtext {
            get {
                return ResourceManager.GetString("Otp_Verification_Subtext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Otp_Verify_Button {
            get {
                return ResourceManager.GetString("Otp_Verify_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use at least 8 characters, with a mixture of Uppercase and Lowercase characters and special symbols..
        /// </summary>
        internal static string Password_Requirements {
            get {
                return ResourceManager.GetString("Password_Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please leave a comment of not more than 100 characters explaining why the application is rejected/accepted..
        /// </summary>
        internal static string Placeholder_Comment {
            get {
                return ResourceManager.GetString("Placeholder_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register with Email.
        /// </summary>
        internal static string Register_Heading {
            get {
                return ResourceManager.GetString("Register_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account using your email address..
        /// </summary>
        internal static string Register_Info {
            get {
                return ResourceManager.GetString("Register_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        internal static string Reset_Password_Heading {
            get {
                return ResourceManager.GetString("Reset_Password_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email to verify your account. You will need to answer your security question..
        /// </summary>
        internal static string Reset_Password_Info {
            get {
                return ResourceManager.GetString("Reset_Password_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security answer verified! Click the button below to send a password reset email..
        /// </summary>
        internal static string Security_Answer_Correct {
            get {
                return ResourceManager.GetString("Security_Answer_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your mother&apos;s maiden name?.
        /// </summary>
        internal static string SecurityQuestion_1 {
            get {
                return ResourceManager.GetString("SecurityQuestion_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the name of your first pet?.
        /// </summary>
        internal static string SecurityQuestion_2 {
            get {
                return ResourceManager.GetString("SecurityQuestion_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your favorite color?.
        /// </summary>
        internal static string SecurityQuestion_3 {
            get {
                return ResourceManager.GetString("SecurityQuestion_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award Badges.
        /// </summary>
        internal static string SideBtnAB {
            get {
                return ResourceManager.GetString("SideBtnAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Management.
        /// </summary>
        internal static string SideBtnAM {
            get {
                return ResourceManager.GetString("SideBtnAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Security.
        /// </summary>
        internal static string SideBtnAS {
            get {
                return ResourceManager.GetString("SideBtnAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Course.
        /// </summary>
        internal static string SideBtnCompletedCourse {
            get {
                return ResourceManager.GetString("SideBtnCompletedCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Management.
        /// </summary>
        internal static string SideBtnCourseManagement {
            get {
                return ResourceManager.GetString("SideBtnCourseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Dashboard.
        /// </summary>
        internal static string SideBtnDb {
            get {
                return ResourceManager.GetString("SideBtnDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string SideBtnInfo {
            get {
                return ResourceManager.GetString("SideBtnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Course.
        /// </summary>
        internal static string SideBtnJoinCourse {
            get {
                return ResourceManager.GetString("SideBtnJoinCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Form.
        /// </summary>
        internal static string SideBtnMAApp {
            get {
                return ResourceManager.GetString("SideBtnMAApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Materials.
        /// </summary>
        internal static string SideBtnMAMat {
            get {
                return ResourceManager.GetString("SideBtnMAMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Course.
        /// </summary>
        internal static string SideBtnMyCourse {
            get {
                return ResourceManager.GetString("SideBtnMyCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string SideBtnPI {
            get {
                return ResourceManager.GetString("SideBtnPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Applications.
        /// </summary>
        internal static string SideBtnRA {
            get {
                return ResourceManager.GetString("SideBtnRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Management.
        /// </summary>
        internal static string SideBtnTM {
            get {
                return ResourceManager.GetString("SideBtnTM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Customisation.
        /// </summary>
        internal static string SideBtnWC {
            get {
                return ResourceManager.GetString("SideBtnWC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Enter Email.
        /// </summary>
        internal static string stepEmail {
            get {
                return ResourceManager.GetString("stepEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Reset Password.
        /// </summary>
        internal static string stepReset {
            get {
                return ResourceManager.GetString("stepReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Security Question.
        /// </summary>
        internal static string stepSecurity {
            get {
                return ResourceManager.GetString("stepSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the 6-digit code sent to you at {0}.
        /// </summary>
        internal static string Subtext_Otp_Verification {
            get {
                return ResourceManager.GetString("Subtext_Otp_Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset email sent. Please check your inbox..
        /// </summary>
        internal static string Success_PasswordResetSent {
            get {
                return ResourceManager.GetString("Success_PasswordResetSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant.
        /// </summary>
        internal static string TableHeader_Applicant {
            get {
                return ResourceManager.GetString("TableHeader_Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application ID.
        /// </summary>
        internal static string TableHeader_ApplicationID {
            get {
                return ResourceManager.GetString("TableHeader_ApplicationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment(s).
        /// </summary>
        internal static string TableHeader_Attachment {
            get {
                return ResourceManager.GetString("TableHeader_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string TableHeader_EmailAddress {
            get {
                return ResourceManager.GetString("TableHeader_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Name.
        /// </summary>
        internal static string TableHeader_EventName {
            get {
                return ResourceManager.GetString("TableHeader_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Outcome.
        /// </summary>
        internal static string TableHeader_LearningOutcome {
            get {
                return ResourceManager.GetString("TableHeader_LearningOutcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string TableHeader_Level {
            get {
                return ResourceManager.GetString("TableHeader_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string TableHeader_PhoneNumber {
            get {
                return ResourceManager.GetString("TableHeader_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string TableHeader_Role {
            get {
                return ResourceManager.GetString("TableHeader_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string TableHeader_Status {
            get {
                return ResourceManager.GetString("TableHeader_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string TableHeader_UserID {
            get {
                return ResourceManager.GetString("TableHeader_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string TableHeader_Username {
            get {
                return ResourceManager.GetString("TableHeader_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger Zone.
        /// </summary>
        internal static string Text_DangerZone {
            get {
                return ResourceManager.GetString("Text_DangerZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Disabling your account will revoke your access to the system. This action cannot be easily undone and may require administrator assistance to restore access..
        /// </summary>
        internal static string Text_DangerZoneWarning {
            get {
                return ResourceManager.GetString("Text_DangerZoneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For security purposes, please enter your current password to continue..
        /// </summary>
        internal static string Text_PasswordVerificationInstructions {
            get {
                return ResourceManager.GetString("Text_PasswordVerificationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: You can earn points via achievement application and earning badges!.
        /// </summary>
        internal static string Tip_EarnPoints {
            get {
                return ResourceManager.GetString("Tip_EarnPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the identified key fields’ position from our AI analysis. By clicking proceed, you can upload a clean template PDF and customise the testimonial certificate!.
        /// </summary>
        internal static string Tip_Testimonial {
            get {
                return ResourceManager.GetString("Tip_Testimonial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string UsernameValue {
            get {
                return ResourceManager.GetString("UsernameValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, {0}!.
        /// </summary>
        internal static string Welcome_Message {
            get {
                return ResourceManager.GetString("Welcome_Message", resourceCulture);
            }
        }
    }
}
